"""Added top 3 careers model

Revision ID: b8403abbdd12
Revises: b9966ee51e9e
Create Date: 2024-09-15 12:10:34.399221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8403abbdd12'
down_revision = 'b9966ee51e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top3_careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_1', sa.String(length=50), nullable=False),
    sa.Column('career_2', sa.String(length=50), nullable=False),
    sa.Column('career_3', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top3_careers')
    # ### end Alembic commands ###
