"""Migration message

Revision ID: b9966ee51e9e
Revises: 
Create Date: 2024-09-14 15:28:29.218723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9966ee51e9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('question_image', sa.String(length=500), nullable=True),
    sa.Column('options_image', sa.String(length=500), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=False),
    sa.Column('fullName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('o_ocean', sa.Float(), nullable=False),
    sa.Column('c_ocean', sa.Float(), nullable=False),
    sa.Column('e_ocean', sa.Float(), nullable=False),
    sa.Column('a_ocean', sa.Float(), nullable=False),
    sa.Column('n_ocean', sa.Float(), nullable=False),
    sa.Column('numeric', sa.Float(), nullable=False),
    sa.Column('spatial', sa.Float(), nullable=False),
    sa.Column('perceptual', sa.Float(), nullable=False),
    sa.Column('abstract', sa.Float(), nullable=False),
    sa.Column('verbal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('user')
    op.drop_table('spatial_questions')
    # ### end Alembic commands ###
